// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account_State int32

const (
	Account_nonstate Account_State = 0
	// Account_CREATE,Account_INITIALIZE
	Account_Initialized Account_State = 1
	// Account_ACTIVATE,Account_UPDATE_PASSWORD
	Account_Activated Account_State = 2
	// Account_LOCK
	Account_Locked Account_State = 3
	// Account_DEACTIVATE
	Account_Deactivated Account_State = 4
)

var Account_State_name = map[int32]string{
	0: "nonstate",
	1: "Initialized",
	2: "Activated",
	3: "Locked",
	4: "Deactivated",
}
var Account_State_value = map[string]int32{
	"nonstate":    0,
	"Initialized": 1,
	"Activated":   2,
	"Locked":      3,
	"Deactivated": 4,
}

func (x Account_State) String() string {
	return proto.EnumName(Account_State_name, int32(x))
}
func (Account_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_5bc0df40fc5eac94, []int{0, 0}
}

type Account_Action int32

const (
	Account_CREATE          Account_Action = 0
	Account_READ            Account_Action = 1
	Account_UPDATE_PASSWORD Account_Action = 2
	Account_ACTIVATE        Account_Action = 3
	Account_DEACTIVATE      Account_Action = 4
	Account_LOCK            Account_Action = 5
	Account_INITIALIZE      Account_Action = 6
)

var Account_Action_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE_PASSWORD",
	3: "ACTIVATE",
	4: "DEACTIVATE",
	5: "LOCK",
	6: "INITIALIZE",
}
var Account_Action_value = map[string]int32{
	"CREATE":          0,
	"READ":            1,
	"UPDATE_PASSWORD": 2,
	"ACTIVATE":        3,
	"DEACTIVATE":      4,
	"LOCK":            5,
	"INITIALIZE":      6,
}

func (x Account_Action) String() string {
	return proto.EnumName(Account_Action_name, int32(x))
}
func (Account_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_account_5bc0df40fc5eac94, []int{0, 1}
}

// A system account to allow access for a subject
type Account struct {
	// `json:"-"`
	Id string `protobuf:"bytes,1,opt,name=id" json:"-"`
	// unique name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// `json:"-"`
	Salt string `protobuf:"bytes,3,opt,name=salt" json:"-"`
	// `json:"-"`
	Hash string `protobuf:"bytes,4,opt,name=hash" json:"-"`
	// []role.proto:Role.name
	Roles                []string      `protobuf:"bytes,5,rep,name=roles" json:"roles,omitempty"`
	State                Account_State `protobuf:"varint,6,opt,name=state,enum=Account_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_5bc0df40fc5eac94, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *Account) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Account) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Account) GetState() Account_State {
	if m != nil {
		return m.State
	}
	return Account_nonstate
}

func init() {
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterEnum("Account_State", Account_State_name, Account_State_value)
	proto.RegisterEnum("Account_Action", Account_Action_name, Account_Action_value)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_5bc0df40fc5eac94) }

var fileDescriptor_account_5bc0df40fc5eac94 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0xe9, 0xaf, 0x70, 0x95, 0x32, 0xb9, 0xba, 0xe8, 0x92, 0x10, 0x17, 0xac, 0x58, 0xe8,
	0x13, 0x8c, 0xb4, 0x8b, 0x46, 0x22, 0x64, 0xa8, 0x9a, 0xb0, 0x31, 0x63, 0x3b, 0x09, 0x13, 0x70,
	0xc6, 0xb4, 0x83, 0x89, 0x3e, 0xa6, 0x4f, 0x64, 0x6e, 0x6b, 0xd8, 0x9d, 0xf3, 0x9d, 0x6f, 0x72,
	0x93, 0x81, 0xb1, 0xac, 0x2a, 0x7b, 0x32, 0x6e, 0xf1, 0xd9, 0x58, 0x67, 0x67, 0xbf, 0x3e, 0x5c,
	0xf0, 0x9e, 0x60, 0x02, 0xbe, 0xae, 0x53, 0x6f, 0xea, 0xcd, 0x47, 0xc2, 0xd7, 0x35, 0x22, 0x84,
	0x46, 0x7e, 0xa8, 0xd4, 0xef, 0x48, 0x97, 0x89, 0xb5, 0xf2, 0xe8, 0xd2, 0xa0, 0x67, 0x94, 0x89,
	0xed, 0x65, 0xbb, 0x4f, 0xc3, 0x9e, 0x51, 0xc6, 0x1b, 0x88, 0x1a, 0x7b, 0x54, 0x6d, 0x1a, 0x4d,
	0x83, 0xf9, 0x48, 0xf4, 0x05, 0x6f, 0x21, 0x6a, 0x9d, 0x74, 0x2a, 0x8d, 0xa7, 0xde, 0x3c, 0xb9,
	0x4b, 0x16, 0xff, 0xa7, 0x17, 0x5b, 0xa2, 0xa2, 0x1f, 0x67, 0x02, 0xa2, 0xae, 0xe3, 0x15, 0x0c,
	0x8d, 0x35, 0x1d, 0x64, 0x03, 0x9c, 0xc0, 0x65, 0x61, 0xb4, 0xd3, 0xf2, 0xa8, 0x7f, 0x54, 0xcd,
	0x3c, 0x1c, 0xc3, 0x88, 0x57, 0x4e, 0x7f, 0x49, 0xa7, 0x6a, 0xe6, 0x23, 0x40, 0xbc, 0xb2, 0xd5,
	0x41, 0xd5, 0x2c, 0x20, 0x37, 0x53, 0xf2, 0x3c, 0x86, 0xb3, 0x03, 0xc4, 0xe4, 0x5a, 0x43, 0xda,
	0x52, 0xe4, 0xbc, 0xcc, 0xd9, 0x00, 0x87, 0x10, 0x8a, 0x9c, 0x67, 0xcc, 0xc3, 0x6b, 0x98, 0x3c,
	0x6f, 0x32, 0x5e, 0xe6, 0x6f, 0x1b, 0xbe, 0xdd, 0xbe, 0xae, 0x45, 0xc6, 0x7c, 0xba, 0xcf, 0x97,
	0x65, 0xf1, 0x42, 0x72, 0x80, 0x09, 0x40, 0x96, 0x9f, 0x7b, 0x48, 0x8f, 0x57, 0xeb, 0xe5, 0x23,
	0x8b, 0x68, 0x29, 0x9e, 0x8a, 0xb2, 0xe0, 0xab, 0x62, 0x97, 0xb3, 0xf8, 0x01, 0x76, 0xc3, 0x56,
	0x55, 0xa7, 0x46, 0xbb, 0xef, 0xf7, 0xb8, 0xfb, 0xe7, 0xfb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xd3, 0xaf, 0x11, 0x58, 0x78, 0x01, 0x00, 0x00,
}
