// Code generated by protoc-gen-go. DO NOT EDIT.
// source: permission.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Permission_Action int32

const (
	Permission_CREATE Permission_Action = 0
	Permission_READ   Permission_Action = 1
	Permission_UPDATE Permission_Action = 2
	Permission_DELETE Permission_Action = 3
)

var Permission_Action_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE",
	3: "DELETE",
}
var Permission_Action_value = map[string]int32{
	"CREATE": 0,
	"READ":   1,
	"UPDATE": 2,
	"DELETE": 3,
}

func (x Permission_Action) String() string {
	return proto.EnumName(Permission_Action_name, int32(x))
}
func (Permission_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_permission_e1afe072022335fe, []int{0, 0}
}

type Permission struct {
	Class                string   `protobuf:"bytes,1,opt,name=class" json:"class,omitempty"`
	Actions              []string `protobuf:"bytes,2,rep,name=actions" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_permission_e1afe072022335fe, []int{0}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (dst *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(dst, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Permission) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Permission)(nil), "Permission")
	proto.RegisterEnum("Permission_Action", Permission_Action_name, Permission_Action_value)
}

func init() { proto.RegisterFile("permission.proto", fileDescriptor_permission_e1afe072022335fe) }

var fileDescriptor_permission_e1afe072022335fe = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x48, 0x2d, 0xca,
	0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x2a, 0xe1, 0xe2,
	0x0a, 0x80, 0x8b, 0x09, 0x89, 0x70, 0xb1, 0x26, 0xe7, 0x24, 0x16, 0x17, 0x4b, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0xc5,
	0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x19, 0x17, 0x9b, 0x23, 0x98, 0x29,
	0xc4, 0xc5, 0xc5, 0xe6, 0x1c, 0xe4, 0xea, 0x18, 0xe2, 0x2a, 0xc0, 0x20, 0xc4, 0xc1, 0xc5, 0x12,
	0xe4, 0xea, 0xe8, 0x22, 0xc0, 0x08, 0x12, 0x0d, 0x0d, 0x70, 0x01, 0x89, 0x32, 0x81, 0xd8, 0x2e,
	0xae, 0x3e, 0xae, 0x21, 0xae, 0x02, 0xcc, 0x4e, 0x5c, 0x51, 0x1c, 0xc5, 0xa9, 0xc9, 0xa5, 0x45,
	0x99, 0x25, 0x95, 0x49, 0x6c, 0x60, 0x87, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x78, 0xde,
	0xa9, 0xc4, 0x9c, 0x00, 0x00, 0x00,
}
