// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Policy_State int32

const (
	// not used, zero is considered not set
	Policy_nonstate Policy_State = 0
	Policy_Active   Policy_State = 1
	Policy_Archived Policy_State = 3
)

var Policy_State_name = map[int32]string{
	0: "nonstate",
	1: "Active",
	3: "Archived",
}
var Policy_State_value = map[string]int32{
	"nonstate": 0,
	"Active":   1,
	"Archived": 3,
}

func (x Policy_State) String() string {
	return proto.EnumName(Policy_State_name, int32(x))
}
func (Policy_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 0}
}

type Policy_Action int32

const (
	Policy_READ   Policy_Action = 0
	Policy_UPDATE Policy_Action = 1
)

var Policy_Action_name = map[int32]string{
	0: "READ",
	1: "UPDATE",
}
var Policy_Action_value = map[string]int32{
	"READ":   0,
	"UPDATE": 1,
}

func (x Policy_Action) String() string {
	return proto.EnumName(Policy_Action_name, int32(x))
}
func (Policy_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 1}
}

type Policy struct {
	Account              *Policy_Account  `protobuf:"bytes,16,opt,name=account" json:"account,omitempty"`
	Audit                *Policy_Audit    `protobuf:"bytes,11,opt,name=audit" json:"audit,omitempty"`
	Password             *Policy_Password `protobuf:"bytes,12,opt,name=password" json:"password,omitempty"`
	Role                 *Policy_Role     `protobuf:"bytes,14,opt,name=role" json:"role,omitempty"`
	Session              *Policy_Session  `protobuf:"bytes,15,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetAccount() *Policy_Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Policy) GetAudit() *Policy_Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *Policy) GetPassword() *Policy_Password {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *Policy) GetRole() *Policy_Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Policy) GetSession() *Policy_Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type Policy_Audit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Audit) Reset()         { *m = Policy_Audit{} }
func (m *Policy_Audit) String() string { return proto.CompactTextString(m) }
func (*Policy_Audit) ProtoMessage()    {}
func (*Policy_Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 0}
}
func (m *Policy_Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Audit.Unmarshal(m, b)
}
func (m *Policy_Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Audit.Marshal(b, m, deterministic)
}
func (dst *Policy_Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Audit.Merge(dst, src)
}
func (m *Policy_Audit) XXX_Size() int {
	return xxx_messageInfo_Policy_Audit.Size(m)
}
func (m *Policy_Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Audit proto.InternalMessageInfo

type Policy_Password struct {
	// minimum length, default 8
	LengthMinimum int32 `protobuf:"varint,2,opt,name=lengthMinimum" json:"lengthMinimum,omitempty"`
	LengthMaximum int32 `protobuf:"varint,3,opt,name=lengthMaximum" json:"lengthMaximum,omitempty"`
	// contains 1 alpha, 1 numeric, 1 special
	Pattern string `protobuf:"bytes,4,opt,name=pattern" json:"pattern,omitempty"`
	// New password must not match a previous password
	ReuseMaximum int32 `protobuf:"varint,5,opt,name=reuseMaximum" json:"reuseMaximum,omitempty"`
	// change password on first login
	AuthenticateInitialConsequence string `protobuf:"bytes,6,opt,name=authenticateInitialConsequence" json:"authenticateInitialConsequence,omitempty"`
	// change password before max age
	DurationMaximum            string `protobuf:"bytes,7,opt,name=durationMaximum" json:"durationMaximum,omitempty"`
	DurationMaximumConsequence string `protobuf:"bytes,8,opt,name=durationMaximumConsequence" json:"durationMaximumConsequence,omitempty"`
	// Lock user account after too many failed login attempts
	AuthenticateFailedCountMaximum       int32    `protobuf:"varint,9,opt,name=authenticateFailedCountMaximum" json:"authenticateFailedCountMaximum,omitempty"`
	AuthenticateFailedMaximumConsequence string   `protobuf:"bytes,10,opt,name=authenticateFailedMaximumConsequence" json:"authenticateFailedMaximumConsequence,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{} `json:"-" bson:"-"`
	XXX_unrecognized                     []byte   `json:"-" bson:"-"`
	XXX_sizecache                        int32    `json:"-" bson:"-"`
}

func (m *Policy_Password) Reset()         { *m = Policy_Password{} }
func (m *Policy_Password) String() string { return proto.CompactTextString(m) }
func (*Policy_Password) ProtoMessage()    {}
func (*Policy_Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 1}
}
func (m *Policy_Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Password.Unmarshal(m, b)
}
func (m *Policy_Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Password.Marshal(b, m, deterministic)
}
func (dst *Policy_Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Password.Merge(dst, src)
}
func (m *Policy_Password) XXX_Size() int {
	return xxx_messageInfo_Policy_Password.Size(m)
}
func (m *Policy_Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Password proto.InternalMessageInfo

func (m *Policy_Password) GetLengthMinimum() int32 {
	if m != nil {
		return m.LengthMinimum
	}
	return 0
}

func (m *Policy_Password) GetLengthMaximum() int32 {
	if m != nil {
		return m.LengthMaximum
	}
	return 0
}

func (m *Policy_Password) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Policy_Password) GetReuseMaximum() int32 {
	if m != nil {
		return m.ReuseMaximum
	}
	return 0
}

func (m *Policy_Password) GetAuthenticateInitialConsequence() string {
	if m != nil {
		return m.AuthenticateInitialConsequence
	}
	return ""
}

func (m *Policy_Password) GetDurationMaximum() string {
	if m != nil {
		return m.DurationMaximum
	}
	return ""
}

func (m *Policy_Password) GetDurationMaximumConsequence() string {
	if m != nil {
		return m.DurationMaximumConsequence
	}
	return ""
}

func (m *Policy_Password) GetAuthenticateFailedCountMaximum() int32 {
	if m != nil {
		return m.AuthenticateFailedCountMaximum
	}
	return 0
}

func (m *Policy_Password) GetAuthenticateFailedMaximumConsequence() string {
	if m != nil {
		return m.AuthenticateFailedMaximumConsequence
	}
	return ""
}

type Policy_Role struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Role) Reset()         { *m = Policy_Role{} }
func (m *Policy_Role) String() string { return proto.CompactTextString(m) }
func (*Policy_Role) ProtoMessage()    {}
func (*Policy_Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 2}
}
func (m *Policy_Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Role.Unmarshal(m, b)
}
func (m *Policy_Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Role.Marshal(b, m, deterministic)
}
func (dst *Policy_Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Role.Merge(dst, src)
}
func (m *Policy_Role) XXX_Size() int {
	return xxx_messageInfo_Policy_Role.Size(m)
}
func (m *Policy_Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Role proto.InternalMessageInfo

type Policy_Session struct {
	Single               bool     `protobuf:"varint,2,opt,name=single" json:"single,omitempty"`
	DurationIdle         string   `protobuf:"bytes,3,opt,name=durationIdle" json:"durationIdle,omitempty"`
	IdleConsequence      string   `protobuf:"bytes,4,opt,name=idleConsequence" json:"idleConsequence,omitempty"`
	DurationRenewal      string   `protobuf:"bytes,5,opt,name=durationRenewal" json:"durationRenewal,omitempty"`
	DurationMaximum      string   `protobuf:"bytes,6,opt,name=durationMaximum" json:"durationMaximum,omitempty"`
	Csrf                 bool     `protobuf:"varint,7,opt,name=csrf" json:"csrf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Session) Reset()         { *m = Policy_Session{} }
func (m *Policy_Session) String() string { return proto.CompactTextString(m) }
func (*Policy_Session) ProtoMessage()    {}
func (*Policy_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 3}
}
func (m *Policy_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Session.Unmarshal(m, b)
}
func (m *Policy_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Session.Marshal(b, m, deterministic)
}
func (dst *Policy_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Session.Merge(dst, src)
}
func (m *Policy_Session) XXX_Size() int {
	return xxx_messageInfo_Policy_Session.Size(m)
}
func (m *Policy_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Session proto.InternalMessageInfo

func (m *Policy_Session) GetSingle() bool {
	if m != nil {
		return m.Single
	}
	return false
}

func (m *Policy_Session) GetDurationIdle() string {
	if m != nil {
		return m.DurationIdle
	}
	return ""
}

func (m *Policy_Session) GetIdleConsequence() string {
	if m != nil {
		return m.IdleConsequence
	}
	return ""
}

func (m *Policy_Session) GetDurationRenewal() string {
	if m != nil {
		return m.DurationRenewal
	}
	return ""
}

func (m *Policy_Session) GetDurationMaximum() string {
	if m != nil {
		return m.DurationMaximum
	}
	return ""
}

func (m *Policy_Session) GetCsrf() bool {
	if m != nil {
		return m.Csrf
	}
	return false
}

type Policy_Account struct {
	// auto-lock unused user accounts after 90 days
	InactiveDurationConsequenceLock string `protobuf:"bytes,2,opt,name=inactiveDurationConsequenceLock" json:"inactiveDurationConsequenceLock,omitempty"`
	// auto-deactivate unused user accounts after 180 days
	InactiveDurationConsequenceDeactivate string   `protobuf:"bytes,3,opt,name=inactiveDurationConsequenceDeactivate" json:"inactiveDurationConsequenceDeactivate,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{} `json:"-" bson:"-"`
	XXX_unrecognized                      []byte   `json:"-" bson:"-"`
	XXX_sizecache                         int32    `json:"-" bson:"-"`
}

func (m *Policy_Account) Reset()         { *m = Policy_Account{} }
func (m *Policy_Account) String() string { return proto.CompactTextString(m) }
func (*Policy_Account) ProtoMessage()    {}
func (*Policy_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_24a87177f428ad9d, []int{0, 4}
}
func (m *Policy_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Account.Unmarshal(m, b)
}
func (m *Policy_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Account.Marshal(b, m, deterministic)
}
func (dst *Policy_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Account.Merge(dst, src)
}
func (m *Policy_Account) XXX_Size() int {
	return xxx_messageInfo_Policy_Account.Size(m)
}
func (m *Policy_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Account proto.InternalMessageInfo

func (m *Policy_Account) GetInactiveDurationConsequenceLock() string {
	if m != nil {
		return m.InactiveDurationConsequenceLock
	}
	return ""
}

func (m *Policy_Account) GetInactiveDurationConsequenceDeactivate() string {
	if m != nil {
		return m.InactiveDurationConsequenceDeactivate
	}
	return ""
}

func init() {
	proto.RegisterType((*Policy)(nil), "Policy")
	proto.RegisterType((*Policy_Audit)(nil), "Policy.Audit")
	proto.RegisterType((*Policy_Password)(nil), "Policy.Password")
	proto.RegisterType((*Policy_Role)(nil), "Policy.Role")
	proto.RegisterType((*Policy_Session)(nil), "Policy.Session")
	proto.RegisterType((*Policy_Account)(nil), "Policy.Account")
	proto.RegisterEnum("Policy_State", Policy_State_name, Policy_State_value)
	proto.RegisterEnum("Policy_Action", Policy_Action_name, Policy_Action_value)
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_policy_24a87177f428ad9d) }

var fileDescriptor_policy_24a87177f428ad9d = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x09, 0x6b, 0x93, 0xf4, 0xad, 0xa3, 0x91, 0x0f, 0x28, 0xca, 0x61, 0x54, 0x65, 0x48,
	0x45, 0x42, 0x45, 0x82, 0x3b, 0x52, 0x59, 0x37, 0x31, 0x09, 0xa4, 0xca, 0x1b, 0x17, 0x6e, 0x26,
	0x79, 0xac, 0x16, 0x99, 0x5d, 0x62, 0x67, 0x63, 0xff, 0x0d, 0x57, 0xfe, 0x22, 0xee, 0xfc, 0x25,
	0x28, 0x2f, 0xf1, 0x94, 0x94, 0x6a, 0xdd, 0x2d, 0xf9, 0xbe, 0xdf, 0xab, 0x3f, 0xfb, 0x73, 0x03,
	0xc3, 0xb5, 0xce, 0x65, 0x7a, 0x3b, 0x5b, 0x17, 0xda, 0xea, 0xc9, 0xaf, 0x01, 0xf8, 0x4b, 0x12,
	0xd8, 0x4b, 0x08, 0x44, 0x9a, 0xea, 0x52, 0xd9, 0x38, 0x1a, 0x7b, 0xd3, 0xfd, 0x37, 0xa3, 0x59,
	0xed, 0xcc, 0xe6, 0xb5, 0xcc, 0x9d, 0xcf, 0x9e, 0x43, 0x5f, 0x94, 0x99, 0xb4, 0xf1, 0x3e, 0x81,
	0x07, 0x77, 0x60, 0x25, 0xf2, 0xda, 0x63, 0xaf, 0x20, 0x5c, 0x0b, 0x63, 0x6e, 0x74, 0x91, 0xc5,
	0x43, 0xe2, 0x22, 0xc7, 0x2d, 0x1b, 0x9d, 0xdf, 0x11, 0x6c, 0x0c, 0xbd, 0x42, 0xe7, 0x18, 0x3f,
	0x21, 0x72, 0xe8, 0x48, 0xae, 0x73, 0xe4, 0xe4, 0x54, 0xf9, 0x0c, 0x1a, 0x23, 0xb5, 0x8a, 0x47,
	0xdd, 0x7c, 0xe7, 0xb5, 0xcc, 0x9d, 0x9f, 0x04, 0xd0, 0xa7, 0x28, 0xc9, 0xdf, 0x3d, 0x08, 0xdd,
	0x62, 0xec, 0x08, 0x0e, 0x72, 0x54, 0x97, 0x76, 0xf5, 0x49, 0x2a, 0x79, 0x55, 0x5e, 0xc5, 0x8f,
	0xc7, 0xde, 0xb4, 0xcf, 0xbb, 0x62, 0x8b, 0x12, 0x3f, 0x89, 0xda, 0xeb, 0x50, 0xb5, 0xc8, 0x62,
	0x08, 0xd6, 0xc2, 0x5a, 0x2c, 0x54, 0xdc, 0x1b, 0x7b, 0xd3, 0x01, 0x77, 0xaf, 0x6c, 0x02, 0xc3,
	0x02, 0x4b, 0x83, 0x6e, 0xbc, 0x4f, 0xe3, 0x1d, 0x8d, 0x9d, 0xc2, 0xa1, 0x28, 0xed, 0x0a, 0x95,
	0x95, 0xa9, 0xb0, 0x78, 0xa6, 0xa4, 0x95, 0x22, 0x3f, 0xd6, 0xca, 0xe0, 0x8f, 0x12, 0x55, 0x8a,
	0xb1, 0x4f, 0x3f, 0xba, 0x83, 0x62, 0x53, 0x18, 0x65, 0x65, 0x21, 0xac, 0xd4, 0xca, 0x2d, 0x17,
	0xd0, 0xe0, 0xa6, 0xcc, 0xde, 0x41, 0xb2, 0x21, 0xb5, 0x57, 0x0b, 0x69, 0xe8, 0x1e, 0x62, 0x33,
	0xf1, 0xa9, 0x90, 0x39, 0x66, 0xc7, 0xd5, 0x65, 0x70, 0x0b, 0x0f, 0x68, 0x9f, 0x3b, 0x28, 0xc6,
	0xe1, 0xe8, 0x7f, 0x62, 0x4b, 0x22, 0xa0, 0x44, 0x0f, 0x62, 0x13, 0x1f, 0x7a, 0xd5, 0x35, 0x49,
	0xfe, 0x78, 0x10, 0x34, 0x57, 0x81, 0x3d, 0x05, 0xdf, 0x48, 0x75, 0x99, 0x23, 0x95, 0x1c, 0xf2,
	0xe6, 0xad, 0x6a, 0xc7, 0xed, 0xf2, 0x2c, 0xcb, 0x91, 0xca, 0x1d, 0xf0, 0x8e, 0x56, 0x9d, 0xaa,
	0xcc, 0x72, 0x6c, 0xc7, 0xa9, 0x3b, 0xde, 0x94, 0xdb, 0xe7, 0xcf, 0x51, 0xe1, 0x8d, 0xc8, 0xa9,
	0xee, 0xd6, 0xf9, 0x37, 0xf2, 0xb6, 0xa6, 0xfc, 0xed, 0x4d, 0x31, 0xe8, 0xa5, 0xa6, 0xf8, 0x46,
	0x45, 0x86, 0x9c, 0x9e, 0x93, 0xdf, 0x1e, 0x04, 0xcd, 0x9f, 0x90, 0x7d, 0x80, 0x67, 0x52, 0x89,
	0xd4, 0xca, 0x6b, 0x5c, 0x34, 0xa3, 0xad, 0x48, 0x1f, 0x75, 0xfa, 0x9d, 0xb6, 0x3c, 0xe0, 0xbb,
	0x30, 0x76, 0x01, 0x2f, 0xee, 0x41, 0x16, 0x48, 0x96, 0xb0, 0xee, 0x90, 0x1e, 0x06, 0x4f, 0x5e,
	0x43, 0xff, 0xdc, 0x0a, 0x8b, 0x6c, 0x08, 0xa1, 0xd2, 0xca, 0x54, 0xcf, 0xd1, 0x23, 0x06, 0xe0,
	0xcf, 0x69, 0x3a, 0xf2, 0x2a, 0x67, 0x5e, 0xa4, 0x2b, 0x79, 0x8d, 0x59, 0xb4, 0x37, 0x39, 0xac,
	0x1d, 0xad, 0x58, 0x08, 0x3d, 0x7e, 0x32, 0x5f, 0xd4, 0xf4, 0xe7, 0xe5, 0x62, 0x7e, 0x71, 0x12,
	0x79, 0xef, 0xe1, 0x4b, 0x68, 0x30, 0x2d, 0x0b, 0x69, 0x6f, 0xbf, 0xfa, 0xf4, 0xd5, 0x7a, 0xfb,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x19, 0xc0, 0x42, 0x62, 0xc5, 0x04, 0x00, 0x00,
}
