// Code generated by protoc-gen-go. DO NOT EDIT.
// source: policy.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Policy_Action int32

const (
	Policy_READ Policy_Action = 0
)

var Policy_Action_name = map[int32]string{
	0: "READ",
}
var Policy_Action_value = map[string]int32{
	"READ": 0,
}

func (x Policy_Action) String() string {
	return proto.EnumName(Policy_Action_name, int32(x))
}
func (Policy_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 0}
}

type Policy struct {
	Account              *Policy_Account  `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Audit                *Policy_Audit    `protobuf:"bytes,2,opt,name=audit" json:"audit,omitempty"`
	Password             *Policy_Password `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Role                 *Policy_Role     `protobuf:"bytes,4,opt,name=role" json:"role,omitempty"`
	Session              *Policy_Session  `protobuf:"bytes,5,opt,name=session" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-" bson:"-"`
	XXX_unrecognized     []byte           `json:"-" bson:"-"`
	XXX_sizecache        int32            `json:"-" bson:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetAccount() *Policy_Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Policy) GetAudit() *Policy_Audit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *Policy) GetPassword() *Policy_Password {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *Policy) GetRole() *Policy_Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Policy) GetSession() *Policy_Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type Policy_Account struct {
	LengthMinimum                         int32    `protobuf:"varint,1,opt,name=lengthMinimum" json:"lengthMinimum,omitempty"`
	LengthMaximum                         int32    `protobuf:"varint,2,opt,name=lengthMaximum" json:"lengthMaximum,omitempty"`
	Pattern                               string   `protobuf:"bytes,3,opt,name=pattern" json:"pattern,omitempty"`
	InactiveDurationConsequenceLock       string   `protobuf:"bytes,4,opt,name=inactiveDurationConsequenceLock" json:"inactiveDurationConsequenceLock,omitempty"`
	InactiveDurationConsequenceDeactivate string   `protobuf:"bytes,5,opt,name=inactiveDurationConsequenceDeactivate" json:"inactiveDurationConsequenceDeactivate,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{} `json:"-" bson:"-"`
	XXX_unrecognized                      []byte   `json:"-" bson:"-"`
	XXX_sizecache                         int32    `json:"-" bson:"-"`
}

func (m *Policy_Account) Reset()         { *m = Policy_Account{} }
func (m *Policy_Account) String() string { return proto.CompactTextString(m) }
func (*Policy_Account) ProtoMessage()    {}
func (*Policy_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 0}
}
func (m *Policy_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Account.Unmarshal(m, b)
}
func (m *Policy_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Account.Marshal(b, m, deterministic)
}
func (dst *Policy_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Account.Merge(dst, src)
}
func (m *Policy_Account) XXX_Size() int {
	return xxx_messageInfo_Policy_Account.Size(m)
}
func (m *Policy_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Account proto.InternalMessageInfo

func (m *Policy_Account) GetLengthMinimum() int32 {
	if m != nil {
		return m.LengthMinimum
	}
	return 0
}

func (m *Policy_Account) GetLengthMaximum() int32 {
	if m != nil {
		return m.LengthMaximum
	}
	return 0
}

func (m *Policy_Account) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Policy_Account) GetInactiveDurationConsequenceLock() string {
	if m != nil {
		return m.InactiveDurationConsequenceLock
	}
	return ""
}

func (m *Policy_Account) GetInactiveDurationConsequenceDeactivate() string {
	if m != nil {
		return m.InactiveDurationConsequenceDeactivate
	}
	return ""
}

type Policy_Audit struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Audit) Reset()         { *m = Policy_Audit{} }
func (m *Policy_Audit) String() string { return proto.CompactTextString(m) }
func (*Policy_Audit) ProtoMessage()    {}
func (*Policy_Audit) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 1}
}
func (m *Policy_Audit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Audit.Unmarshal(m, b)
}
func (m *Policy_Audit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Audit.Marshal(b, m, deterministic)
}
func (dst *Policy_Audit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Audit.Merge(dst, src)
}
func (m *Policy_Audit) XXX_Size() int {
	return xxx_messageInfo_Policy_Audit.Size(m)
}
func (m *Policy_Audit) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Audit.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Audit proto.InternalMessageInfo

type Policy_Password struct {
	LengthMinimum                        int32    `protobuf:"varint,1,opt,name=lengthMinimum" json:"lengthMinimum,omitempty"`
	LengthMaximum                        int32    `protobuf:"varint,2,opt,name=lengthMaximum" json:"lengthMaximum,omitempty"`
	Pattern                              string   `protobuf:"bytes,3,opt,name=pattern" json:"pattern,omitempty"`
	ReuseMaximum                         int32    `protobuf:"varint,4,opt,name=reuseMaximum" json:"reuseMaximum,omitempty"`
	AuthenticateInitialConsequence       string   `protobuf:"bytes,5,opt,name=authenticateInitialConsequence" json:"authenticateInitialConsequence,omitempty"`
	DurationMaximum                      string   `protobuf:"bytes,6,opt,name=durationMaximum" json:"durationMaximum,omitempty"`
	DurationMaximumConsequence           string   `protobuf:"bytes,7,opt,name=durationMaximumConsequence" json:"durationMaximumConsequence,omitempty"`
	AuthenticateFailedCountMaximum       int32    `protobuf:"varint,8,opt,name=authenticateFailedCountMaximum" json:"authenticateFailedCountMaximum,omitempty"`
	AuthenticateFailedMaximumConsequence string   `protobuf:"bytes,9,opt,name=authenticateFailedMaximumConsequence" json:"authenticateFailedMaximumConsequence,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{} `json:"-" bson:"-"`
	XXX_unrecognized                     []byte   `json:"-" bson:"-"`
	XXX_sizecache                        int32    `json:"-" bson:"-"`
}

func (m *Policy_Password) Reset()         { *m = Policy_Password{} }
func (m *Policy_Password) String() string { return proto.CompactTextString(m) }
func (*Policy_Password) ProtoMessage()    {}
func (*Policy_Password) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 2}
}
func (m *Policy_Password) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Password.Unmarshal(m, b)
}
func (m *Policy_Password) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Password.Marshal(b, m, deterministic)
}
func (dst *Policy_Password) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Password.Merge(dst, src)
}
func (m *Policy_Password) XXX_Size() int {
	return xxx_messageInfo_Policy_Password.Size(m)
}
func (m *Policy_Password) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Password.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Password proto.InternalMessageInfo

func (m *Policy_Password) GetLengthMinimum() int32 {
	if m != nil {
		return m.LengthMinimum
	}
	return 0
}

func (m *Policy_Password) GetLengthMaximum() int32 {
	if m != nil {
		return m.LengthMaximum
	}
	return 0
}

func (m *Policy_Password) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Policy_Password) GetReuseMaximum() int32 {
	if m != nil {
		return m.ReuseMaximum
	}
	return 0
}

func (m *Policy_Password) GetAuthenticateInitialConsequence() string {
	if m != nil {
		return m.AuthenticateInitialConsequence
	}
	return ""
}

func (m *Policy_Password) GetDurationMaximum() string {
	if m != nil {
		return m.DurationMaximum
	}
	return ""
}

func (m *Policy_Password) GetDurationMaximumConsequence() string {
	if m != nil {
		return m.DurationMaximumConsequence
	}
	return ""
}

func (m *Policy_Password) GetAuthenticateFailedCountMaximum() int32 {
	if m != nil {
		return m.AuthenticateFailedCountMaximum
	}
	return 0
}

func (m *Policy_Password) GetAuthenticateFailedMaximumConsequence() string {
	if m != nil {
		return m.AuthenticateFailedMaximumConsequence
	}
	return ""
}

type Policy_Role struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Role) Reset()         { *m = Policy_Role{} }
func (m *Policy_Role) String() string { return proto.CompactTextString(m) }
func (*Policy_Role) ProtoMessage()    {}
func (*Policy_Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 3}
}
func (m *Policy_Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Role.Unmarshal(m, b)
}
func (m *Policy_Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Role.Marshal(b, m, deterministic)
}
func (dst *Policy_Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Role.Merge(dst, src)
}
func (m *Policy_Role) XXX_Size() int {
	return xxx_messageInfo_Policy_Role.Size(m)
}
func (m *Policy_Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Role proto.InternalMessageInfo

type Policy_Session struct {
	Single               bool     `protobuf:"varint,1,opt,name=single" json:"single,omitempty"`
	DurationIdle         string   `protobuf:"bytes,2,opt,name=durationIdle" json:"durationIdle,omitempty"`
	IdleConsequence      string   `protobuf:"bytes,3,opt,name=idleConsequence" json:"idleConsequence,omitempty"`
	DurationRenewal      string   `protobuf:"bytes,4,opt,name=durationRenewal" json:"durationRenewal,omitempty"`
	DurationMaximum      string   `protobuf:"bytes,5,opt,name=durationMaximum" json:"durationMaximum,omitempty"`
	Csrf                 bool     `protobuf:"varint,6,opt,name=csrf" json:"csrf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Policy_Session) Reset()         { *m = Policy_Session{} }
func (m *Policy_Session) String() string { return proto.CompactTextString(m) }
func (*Policy_Session) ProtoMessage()    {}
func (*Policy_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_policy_0bb8e8e6ca41595a, []int{0, 4}
}
func (m *Policy_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy_Session.Unmarshal(m, b)
}
func (m *Policy_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy_Session.Marshal(b, m, deterministic)
}
func (dst *Policy_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy_Session.Merge(dst, src)
}
func (m *Policy_Session) XXX_Size() int {
	return xxx_messageInfo_Policy_Session.Size(m)
}
func (m *Policy_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Policy_Session proto.InternalMessageInfo

func (m *Policy_Session) GetSingle() bool {
	if m != nil {
		return m.Single
	}
	return false
}

func (m *Policy_Session) GetDurationIdle() string {
	if m != nil {
		return m.DurationIdle
	}
	return ""
}

func (m *Policy_Session) GetIdleConsequence() string {
	if m != nil {
		return m.IdleConsequence
	}
	return ""
}

func (m *Policy_Session) GetDurationRenewal() string {
	if m != nil {
		return m.DurationRenewal
	}
	return ""
}

func (m *Policy_Session) GetDurationMaximum() string {
	if m != nil {
		return m.DurationMaximum
	}
	return ""
}

func (m *Policy_Session) GetCsrf() bool {
	if m != nil {
		return m.Csrf
	}
	return false
}

func init() {
	proto.RegisterType((*Policy)(nil), "Policy")
	proto.RegisterType((*Policy_Account)(nil), "Policy.Account")
	proto.RegisterType((*Policy_Audit)(nil), "Policy.Audit")
	proto.RegisterType((*Policy_Password)(nil), "Policy.Password")
	proto.RegisterType((*Policy_Role)(nil), "Policy.Role")
	proto.RegisterType((*Policy_Session)(nil), "Policy.Session")
	proto.RegisterEnum("Policy_Action", Policy_Action_name, Policy_Action_value)
}

func init() { proto.RegisterFile("policy.proto", fileDescriptor_policy_0bb8e8e6ca41595a) }

var fileDescriptor_policy_0bb8e8e6ca41595a = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0x49, 0xba, 0xd9, 0x3f, 0x43, 0xaa, 0x56, 0x3e, 0xa0, 0xd5, 0x1e, 0xa0, 0x0a, 0x45,
	0x2a, 0x12, 0xca, 0x01, 0xee, 0x48, 0xa1, 0xa1, 0xa2, 0x12, 0x48, 0x95, 0xe1, 0xc4, 0xcd, 0x78,
	0x87, 0xd6, 0xc2, 0xb5, 0xc3, 0xda, 0x4b, 0xe9, 0x53, 0xf0, 0x5c, 0x3c, 0x01, 0x77, 0x9e, 0x04,
	0xed, 0xec, 0xba, 0xca, 0x2e, 0x51, 0xd3, 0x53, 0x6f, 0xd9, 0x6f, 0x7e, 0x23, 0xcf, 0x37, 0x9f,
	0x1d, 0x98, 0xae, 0xac, 0x56, 0xf2, 0x7a, 0xbe, 0xaa, 0xac, 0xb7, 0xb3, 0xdf, 0x19, 0xc4, 0x67,
	0x24, 0xb0, 0xe7, 0x90, 0x08, 0x29, 0x6d, 0x6d, 0x7c, 0x3e, 0x3a, 0x18, 0x1d, 0x3d, 0x7c, 0xb9,
	0x37, 0x6f, 0x2b, 0xf3, 0x45, 0x2b, 0xf3, 0x50, 0x67, 0x4f, 0x61, 0x22, 0xea, 0x52, 0xf9, 0x7c,
	0x4c, 0xe0, 0xee, 0x0d, 0xd8, 0x88, 0xbc, 0xad, 0xb1, 0x17, 0x90, 0xae, 0x84, 0x73, 0x57, 0xb6,
	0x2a, 0xf3, 0x1d, 0xe2, 0xf6, 0x03, 0x77, 0xd6, 0xe9, 0xfc, 0x86, 0x60, 0x07, 0x10, 0x55, 0x56,
	0x63, 0x1e, 0x11, 0x39, 0x0d, 0x24, 0xb7, 0x1a, 0x39, 0x55, 0x9a, 0xf9, 0x1c, 0x3a, 0xa7, 0xac,
	0xc9, 0x27, 0xfd, 0xf9, 0x3e, 0xb6, 0x32, 0x0f, 0xf5, 0xe2, 0xd7, 0x18, 0x92, 0x6e, 0x68, 0x76,
	0x08, 0xbb, 0x1a, 0xcd, 0xb9, 0xbf, 0xf8, 0xa0, 0x8c, 0xba, 0xac, 0x2f, 0xc9, 0xdc, 0x84, 0xf7,
	0xc5, 0x35, 0x4a, 0xfc, 0x24, 0x6a, 0xdc, 0xa3, 0x5a, 0x91, 0xe5, 0x90, 0xac, 0x84, 0xf7, 0x58,
	0x19, 0x72, 0x94, 0xf1, 0xf0, 0xc9, 0xde, 0xc1, 0x13, 0x65, 0x84, 0xf4, 0xea, 0x07, 0x2e, 0xeb,
	0x4a, 0x78, 0x65, 0xcd, 0xb1, 0x35, 0x0e, 0xbf, 0xd7, 0x68, 0x24, 0xbe, 0xb7, 0xf2, 0x1b, 0x39,
	0xcb, 0xf8, 0x36, 0x8c, 0x7d, 0x82, 0x67, 0xb7, 0x20, 0x4b, 0xa4, 0x92, 0xf0, 0x48, 0x4b, 0xc8,
	0xf8, 0xdd, 0xe0, 0x22, 0x81, 0x09, 0x85, 0x53, 0xfc, 0xdd, 0x81, 0x34, 0xac, 0xff, 0x9e, 0x76,
	0x33, 0x83, 0x69, 0x85, 0xb5, 0xc3, 0xd0, 0x1e, 0x51, 0x7b, 0x4f, 0x63, 0x27, 0xf0, 0x58, 0xd4,
	0xfe, 0x02, 0x8d, 0x57, 0x52, 0x78, 0x3c, 0x35, 0xca, 0x2b, 0xa1, 0xd7, 0xbc, 0x74, 0x76, 0xb7,
	0x50, 0xec, 0x08, 0xf6, 0xca, 0x6e, 0x11, 0xe1, 0xb8, 0x98, 0x1a, 0x87, 0x32, 0x7b, 0x0d, 0xc5,
	0x40, 0x5a, 0x3f, 0x2d, 0xa1, 0xa6, 0x5b, 0x88, 0xe1, 0xc4, 0x27, 0x42, 0x69, 0x2c, 0x8f, 0x9b,
	0x2b, 0x17, 0x0e, 0x4e, 0xc9, 0xe7, 0x16, 0x8a, 0x71, 0x38, 0xfc, 0x9f, 0xd8, 0x30, 0x51, 0x46,
	0x13, 0xdd, 0x89, 0x2d, 0x62, 0x88, 0x9a, 0x87, 0x53, 0xfc, 0x19, 0x41, 0xd2, 0x3d, 0x0e, 0xf6,
	0x08, 0x62, 0xa7, 0xcc, 0xb9, 0x46, 0x0a, 0x39, 0xe5, 0xdd, 0x57, 0x93, 0x4e, 0x70, 0x79, 0x5a,
	0x6a, 0xa4, 0x70, 0x33, 0xde, 0xd3, 0x9a, 0xad, 0xaa, 0x52, 0xe3, 0xfa, 0x38, 0x6d, 0xc6, 0x43,
	0x79, 0x7d, 0xff, 0x1c, 0x0d, 0x5e, 0x09, 0xdd, 0xdd, 0xfb, 0xa1, 0xbc, 0x29, 0xa9, 0xc9, 0xe6,
	0xa4, 0x18, 0x44, 0xd2, 0x55, 0x5f, 0x29, 0xc8, 0x94, 0xd3, 0xef, 0x19, 0x83, 0x78, 0x21, 0x1b,
	0x88, 0xa5, 0x10, 0xf1, 0xb7, 0x8b, 0xe5, 0xfe, 0x83, 0x37, 0xf0, 0x39, 0x75, 0x28, 0xeb, 0x4a,
	0xf9, 0xeb, 0x2f, 0x31, 0xfd, 0xbd, 0xbd, 0xfa, 0x17, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x90, 0x3a,
	0xe6, 0xee, 0x04, 0x00, 0x00,
}
