// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role_State int32

const (
	Role_nonstate Role_State = 0
	// Role_CREATE
	Role_Initialized Role_State = 1
	// Role_ACTIVATE
	Role_Activated Role_State = 2
	// Role_DEACTIVATE
	Role_Deactivated Role_State = 3
)

var Role_State_name = map[int32]string{
	0: "nonstate",
	1: "Initialized",
	2: "Activated",
	3: "Deactivated",
}
var Role_State_value = map[string]int32{
	"nonstate":    0,
	"Initialized": 1,
	"Activated":   2,
	"Deactivated": 3,
}

func (x Role_State) String() string {
	return proto.EnumName(Role_State_name, int32(x))
}
func (Role_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_role_e1761b71c19178cb, []int{0, 0}
}

type Role_Action int32

const (
	Role_CREATE     Role_Action = 0
	Role_READ       Role_Action = 1
	Role_UPDATE     Role_Action = 2
	Role_DELETE     Role_Action = 3
	Role_ACTIVATE   Role_Action = 4
	Role_DEACTIVATE Role_Action = 5
)

var Role_Action_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE",
	3: "DELETE",
	4: "ACTIVATE",
	5: "DEACTIVATE",
}
var Role_Action_value = map[string]int32{
	"CREATE":     0,
	"READ":       1,
	"UPDATE":     2,
	"DELETE":     3,
	"ACTIVATE":   4,
	"DEACTIVATE": 5,
}

func (x Role_Action) String() string {
	return proto.EnumName(Role_Action_name, int32(x))
}
func (Role_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_role_e1761b71c19178cb, []int{0, 1}
}

// A named collection of permissions
type Role struct {
	// unique name
	Name                 string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	State                Role_State    `protobuf:"varint,2,opt,name=state,enum=Role_State" json:"state,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,3,rep,name=permissions" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_role_e1761b71c19178cb, []int{0}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Role) GetState() Role_State {
	if m != nil {
		return m.State
	}
	return Role_nonstate
}

func (m *Role) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*Role)(nil), "Role")
	proto.RegisterEnum("Role_State", Role_State_name, Role_State_value)
	proto.RegisterEnum("Role_Action", Role_Action_name, Role_Action_value)
}

func init() { proto.RegisterFile("role.proto", fileDescriptor_role_e1761b71c19178cb) }

var fileDescriptor_role_e1761b71c19178cb = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x9b, 0xbf, 0x4a, 0xcf, 0x50, 0xac, 0x9b, 0x22, 0xa6, 0x90, 0x29, 0x0b, 0x19, 0xca,
	0x13, 0x84, 0xda, 0x48, 0x95, 0x18, 0x2a, 0x13, 0x18, 0xd8, 0x4c, 0xeb, 0xc1, 0x52, 0x6a, 0x57,
	0xb1, 0x41, 0x82, 0x47, 0xe0, 0xa9, 0x91, 0x53, 0x29, 0x74, 0xfb, 0xfc, 0xfb, 0xf9, 0xbe, 0x93,
	0x0e, 0x60, 0xb4, 0x83, 0x6a, 0x4f, 0xa3, 0xf5, 0xf6, 0x96, 0x9e, 0xd4, 0x78, 0xd4, 0xce, 0x69,
	0x6b, 0xce, 0xa4, 0xfe, 0x8d, 0x21, 0x15, 0x76, 0x50, 0x88, 0x90, 0x1a, 0x79, 0x54, 0x65, 0x54,
	0x45, 0xcd, 0x52, 0x4c, 0x19, 0xef, 0x20, 0x73, 0x5e, 0x7a, 0x55, 0xc6, 0x55, 0xd4, 0xac, 0xd6,
	0xa4, 0x0d, 0x3f, 0xdb, 0x97, 0x80, 0xc4, 0xd9, 0xe0, 0x3d, 0x90, 0xff, 0x4e, 0x57, 0x26, 0x55,
	0xd2, 0x90, 0x35, 0x69, 0x77, 0x33, 0x13, 0x97, 0xbe, 0x7e, 0x82, 0x6c, 0x1a, 0xc7, 0x2b, 0x28,
	0x8c, 0x35, 0x53, 0x07, 0x5d, 0xe0, 0x0d, 0x90, 0xad, 0xd1, 0x5e, 0xcb, 0x41, 0xff, 0xa8, 0x03,
	0x8d, 0xf0, 0x1a, 0x96, 0xdd, 0xde, 0xeb, 0x2f, 0xe9, 0xd5, 0x81, 0xc6, 0xc1, 0x33, 0x25, 0x67,
	0x90, 0xd4, 0x3d, 0xe4, 0xc1, 0x5b, 0x83, 0x00, 0xf9, 0x46, 0xf0, 0xae, 0xe7, 0x74, 0x81, 0x05,
	0xa4, 0x82, 0x77, 0x8c, 0x46, 0x81, 0xbe, 0xee, 0x58, 0xa0, 0x71, 0xc8, 0x8c, 0x3f, 0xf3, 0x9e,
	0xd3, 0x24, 0xac, 0xed, 0x36, 0xfd, 0xf6, 0x2d, 0x98, 0x14, 0x57, 0x00, 0x8c, 0xcf, 0xef, 0xec,
	0x11, 0xde, 0x0b, 0xa7, 0xf6, 0x9f, 0xa3, 0xf6, 0xdf, 0x1f, 0xf9, 0x74, 0x9f, 0x87, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0b, 0xcd, 0x52, 0x07, 0x3f, 0x01, 0x00, 0x00,
}
