// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package security

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session_State int32

const (
	Session_initial Session_State = 0
	// Action:CREATE
	Session_Activated Session_State = 2
	// Action:IDLE,Action:REDUCE
	Session_Reduced Session_State = 3
	// Action:EXPIRE,TERMINATE
	Session_Deactivated Session_State = 5
)

var Session_State_name = map[int32]string{
	0: "initial",
	2: "Activated",
	3: "Reduced",
	5: "Deactivated",
}
var Session_State_value = map[string]int32{
	"initial":     0,
	"Activated":   2,
	"Reduced":     3,
	"Deactivated": 5,
}

func (x Session_State) String() string {
	return proto.EnumName(Session_State_name, int32(x))
}
func (Session_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_session_e45b68d640e40c59, []int{0, 0}
}

type Session_Action int32

const (
	Session_CREATE    Session_Action = 0
	Session_READ      Session_Action = 1
	Session_IDLE      Session_Action = 2
	Session_EXPIRE    Session_Action = 3
	Session_TERMINATE Session_Action = 4
	Session_REDUCE    Session_Action = 5
)

var Session_Action_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "IDLE",
	3: "EXPIRE",
	4: "TERMINATE",
	5: "REDUCE",
}
var Session_Action_value = map[string]int32{
	"CREATE":    0,
	"READ":      1,
	"IDLE":      2,
	"EXPIRE":    3,
	"TERMINATE": 4,
	"REDUCE":    5,
}

func (x Session_Action) String() string {
	return proto.EnumName(Session_Action_name, int32(x))
}
func (Session_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_session_e45b68d640e40c59, []int{0, 1}
}

// A container of time-limited permissions shared with a subject
type Session struct {
	// `json:"-"`
	Id string `protobuf:"bytes,1,opt,name=id" json:"-"`
	// privately shared identifier `json:"-"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId" json:"-"`
	// account.proto:Account.name
	Account              string        `protobuf:"bytes,3,opt,name=account" json:"account,omitempty"`
	Csrf                 string        `protobuf:"bytes,4,opt,name=csrf" json:"csrf,omitempty"`
	Permissions          []*Permission `protobuf:"bytes,5,rep,name=permissions" json:"permissions,omitempty"`
	State                Session_State `protobuf:"varint,6,opt,name=state,enum=Session_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-" bson:"-"`
	XXX_unrecognized     []byte        `json:"-" bson:"-"`
	XXX_sizecache        int32         `json:"-" bson:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_e45b68d640e40c59, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Session) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Session) GetCsrf() string {
	if m != nil {
		return m.Csrf
	}
	return ""
}

func (m *Session) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Session) GetState() Session_State {
	if m != nil {
		return m.State
	}
	return Session_initial
}

func init() {
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterEnum("Session_State", Session_State_name, Session_State_value)
	proto.RegisterEnum("Session_Action", Session_Action_name, Session_Action_value)
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_session_e45b68d640e40c59) }

var fileDescriptor_session_e45b68d640e40c59 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x6a, 0x32, 0x31,
	0x14, 0x86, 0x9d, 0xcc, 0x8f, 0x7a, 0x06, 0xfd, 0xc2, 0x59, 0x85, 0x8f, 0x2e, 0x44, 0xba, 0x70,
	0xd3, 0x59, 0xd8, 0x2b, 0x98, 0x3a, 0x59, 0x0c, 0xf4, 0x47, 0xa2, 0x85, 0xd2, 0xdd, 0x34, 0x49,
	0x21, 0xd0, 0xce, 0xc8, 0x24, 0x16, 0x7a, 0x93, 0xbd, 0xa6, 0x92, 0x68, 0xd5, 0xdd, 0x39, 0xcf,
	0xf3, 0x86, 0x37, 0x1c, 0x98, 0x58, 0x6d, 0xad, 0xe9, 0xda, 0x62, 0xd7, 0x77, 0xae, 0xfb, 0x4f,
	0x77, 0xba, 0xff, 0x34, 0x17, 0x64, 0xfe, 0x43, 0x60, 0xb8, 0x39, 0x64, 0x70, 0x0a, 0xc4, 0x28,
	0x16, 0xcd, 0xa2, 0xc5, 0x58, 0x10, 0xa3, 0xf0, 0x0a, 0xc6, 0xc7, 0xe7, 0xb5, 0x62, 0x24, 0xe0,
	0x33, 0x40, 0x06, 0xc3, 0x46, 0xca, 0x6e, 0xdf, 0x3a, 0x16, 0x07, 0xf7, 0xb7, 0x22, 0x42, 0x22,
	0x6d, 0xff, 0xce, 0x92, 0x80, 0xc3, 0x8c, 0x37, 0x90, 0x9f, 0xbb, 0x2d, 0x4b, 0x67, 0xf1, 0x22,
	0x5f, 0xe6, 0xc5, 0xfa, 0xc4, 0xc4, 0xa5, 0xc7, 0x6b, 0x48, 0xad, 0x6b, 0x9c, 0x66, 0xd9, 0x2c,
	0x5a, 0x4c, 0x97, 0xd3, 0xe2, 0xf8, 0xc7, 0x62, 0xe3, 0xa9, 0x38, 0xc8, 0x79, 0x09, 0x69, 0xd8,
	0x31, 0x87, 0xa1, 0x69, 0x8d, 0x33, 0xcd, 0x07, 0x1d, 0xe0, 0x04, 0xc6, 0xa5, 0x74, 0xe6, 0xab,
	0x71, 0x5a, 0x51, 0xe2, 0x9d, 0xd0, 0x6a, 0x2f, 0xb5, 0xa2, 0x31, 0xfe, 0x83, 0xbc, 0xd2, 0xcd,
	0xc9, 0xa6, 0xf3, 0x27, 0xc8, 0x7c, 0xb8, 0x6b, 0x11, 0x20, 0x5b, 0x09, 0x5e, 0x6e, 0x39, 0x1d,
	0xe0, 0x08, 0x12, 0xc1, 0xcb, 0x8a, 0x46, 0x7e, 0xaa, 0xab, 0x7b, 0x4e, 0x89, 0xf7, 0xfc, 0x65,
	0x5d, 0x0b, 0x4e, 0x63, 0x5f, 0xb1, 0xe5, 0xe2, 0xa1, 0x7e, 0xf4, 0xf1, 0xc4, 0x2b, 0xc1, 0xab,
	0xe7, 0x15, 0xa7, 0xe9, 0x1d, 0xbc, 0x8e, 0xac, 0x96, 0xfb, 0xde, 0xb8, 0xef, 0xb7, 0x2c, 0xdc,
	0xf8, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0xec, 0xd7, 0xf2, 0x90, 0x86, 0x01, 0x00, 0x00,
}
